first chaleng creating phone number with slice and join
xikaojr/fdev007 pull request #1
Opened 2024-02-24 22:27 UTC by vicentepaiva

feature:  creating first task adding new phone from array.

2024-02-25 13:07 UTC, xikaojr requested changes

2024-02-25 13:07 UTC, xikaojr commented on index.js
1º já que você definiu uma const no topo da aplicação com o array de numbers, a chamada da função na linha 10 não precisaria passar nada por parâmetro.

2º como na chamada (linha 10) vc passou numbers por parâmetro, você precisaria injetar estes parâmetros na criação da função (linha 4) perceba que sua função não esta recebendo nada;

3º já que numbers é uma const fixa no topo, não precisaria usar aquele let phoneNUmber, poderia ter acessado diretamente a const numbers declarada lá fora !!

2024-02-25 14:16 UTC, vicentepaiva commented
refact carried out

2024-02-27 11:01 UTC, xikaojr approved these changes

2024-04-04 14:14 UTC, closed without merging